---
title: "Getting and Cleaning Data - Course Project"
output: html_document
---


### Summary

One of the most exciting areas in all of data science right now is wearable computing - see for example **[this article](http://cs229.stanford.edu/proj2013/BrownDeitchOConor-ActivityClassificationwithSmartphoneData.pdf)** . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained: 


http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

 Here are the data for the project: 

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 


After downloading and unziping, you can find data set information in the ReadMe.txt of UCI HAR Dataset directory.


#### The purpose of this project is to prepare tidy data that can be used for later analysis.


### The R script called run_analysis.R does the following:

1. Read data and apply labels the data set with descriptive variable names. 
2. Merges the training and the test sets to create one data set.
3. Extracts only the measurements on the mean and standard deviation for each 
4. Uses descriptive activity names to name the activities in the data set
5. From the data set in step 4, creates tidy data set with the average of each         variable for each activity and each subject.



To run this R script, the directory of data set should be ./data/UCI HAR Dataset.

The detail flow of R script can be found in the R script.


The variable description can be found in the Codebook.md in this repo.
